# Generated by Django 5.0.7 on 2024-07-30 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['crn'], 'verbose_name': 'Class Section', 'verbose_name_plural': 'Class Sections'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='section',
            name='days',
        ),
        migrations.RemoveField(
            model_name='section',
            name='end_time',
        ),
        migrations.CreateModel(
            name='SectionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.section')),
            ],
            options={
                'verbose_name': 'Section Time',
                'verbose_name_plural': 'Section Times',
            },
        ),
    ]
